sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  aws:
    access-key: AKIA4MTWNVFE6HLQEBN5
    secret-key: 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
    region: ap-northeast-1
    bucket-name: sky-itcast1
#    endpoint:

  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10